### ISSUE TITLE
Backend for EAS-Onboarding dApp

### ISSUE THREAD

**Issue by shyam-patel-kira** [zenbitETH/eas-onboarding#6]
Write Backend for onBoarding dApp

- [x] Create model for Events/quiz
- [x] integrate dB for storage
- [x] add queries for frontend
- [x] FrontEnd Integration
- [x] Second Event for attestation
- [x] Modify models for the second event attestations

**Comment by Dharmik79** [comment]
@shyam-patel-kira Not able to create the event from the frontend.

SO, for now, the read contracts on the homePage is remaining to update the call function and now quiz check API is remaining.So, by tomorrow it will be done

**Comment by shyam-patel-kira** [comment]
@Dharmik79, We have some more updates for 2nd Event
